import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import Navbar from './components/Navbar'
import Loginbtn from "./Loginbtn";
import Logoutbtn from "./Logoutbtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Register from "./register";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 서버 세션 가져오기
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex', flexDirection: 'column' }}>
            <Navbar />
            <div style={{ paddingTop: '100px', flexGrow: 1 }}>
              {children}
            </div>
      </body>
    </html>
  );
}
