import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import Navbar from './components/Navbar'
import styles from './globals.css';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex', flexDirection: 'column' }}>
        <Navbar/>
        <div style={{ paddingTop: '100px', flexGrow: 1 }}>
          {children}
        </div>
      </body>
    </html>
      
  );
}
